wheelbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Effort Controllers ---------------------------------------
  base_to_caster_wheel_yaw_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_to_caster_wheel_yaw
    pid: {p: 100.0, i: 0.01, d: 10.0}
