<?xml version="1.0"?>
<robot name="common" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="custom_inertia" params="mass ixx:=1 iyy:=1 izz:=1">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${ixx}" ixy="0"      ixz="0" 
                            iyy="${iyy}" iyz="0"
                                         izz="${izz}" />
    </inertial>
  </xacro:macro>

  <!-- See "List of moments of inertia" in Wikipedia -->
  <xacro:macro name="cylinder_inertia" params="mass radius length">
    <xacro:custom_inertia mass="${mass}" 
      ixx="${1/12 * mass * (3 * pow(radius, 2) + pow(length, 2))}" 
      iyy="${1/12 * mass * (3 * pow(radius, 2) + pow(length, 2))}" 
      izz="${1/2 * mass * pow(radius, 2)}" />
  </xacro:macro>

  <xacro:macro name="cuboid_inertia" params="mass width height depth">
    <xacro:custom_inertia mass="${mass}" 
          ixx="${1/12 * mass * (pow(width, 2) + pow(depth, 2))}" 
          iyy="${1/12 * mass * (pow(width, 2) + pow(depth, 2))}" 
          izz="${1/12 * mass * (pow(width, 2) + pow(height, 2))}" />
  </xacro:macro>

  <xacro:macro name="side_wheel" params="prefix reflect:=1">
    <link name="${prefix}_wheel">
      <visual>
        <material name="Red" />
        <geometry>
          <cylinder length="${side_wheel_length}" radius="${side_wheel_radius}" />
        </geometry>
      </visual>
      
      <collision>
        <geometry>
          <cylinder length="${side_wheel_length}" radius="${side_wheel_radius}" />
        </geometry>
      </collision>

      <xacro:cylinder_inertia mass="${side_wheel_mass}" 
        radius="${side_wheel_radius}" length="${side_wheel_length}" />
    </link>

    <joint name="base_to_${prefix}_wheel" type="continuous">
      <parent link="base_link" />
      <child link="${prefix}_wheel" />
      <axis xyz="0 0 1" />
      <origin xyz="${body_width/3} ${reflect * (body_height/2 + side_wheel_length/2)} -${body_depth/2 - side_wheel_offset_z}" 
        rpy="0 ${pi/2} ${pi/2}" />
    </joint>
  </xacro:macro>

</robot>